env:
  NODE_ENV: test
  # SLACK_WEBHOOK_URL should be added as a secret in Buildkite UI (Pipeline > Settings > Secrets)

steps:
  - group: "Cypress Test Suite"
    steps:
      - label: ":hammer: Install & Run Tests"
        key: "cypress-tests"
        command: |
          echo "Installing dependencies..."
          npm ci
          echo "✅ Dependencies installed!"

          echo "Installing system dependencies for Cypress..."
          sudo apt-get update -qq
          sudo apt-get install -y -qq \
            xvfb \
            libgtk-3-0 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2 \
            libxtst6 \
            xauth

          echo "Verifying Cypress installation..."
          npx cypress verify

          echo "🚀 Running Cypress tests..."
          npm run test:slack   # runs slackReporter.js to send report to Slack
